build_targets:
- commands:
  - chmod +x yourbased.sh
  - sh ./yourbased.sh
  container:
    image: yourbase/yb_ubuntu:16.04
  name: default
  environment:
  - DB=postgresql
  - DB_USERNAME=root
  - DB_PASSWORD=root
  - DB_HOST={{ .Containers.IP "db" }}
  - REDISCLOUD_URL=redis://{{ .Containers.IP "redis" }}:6379/
#   - DATABASE_URL=postgres://ci:ci@{{ .Containers.IP "db" }}:5432/travis_ci_test
  dependencies:
      containers:
        redis:
          image: redis:latest
          port_check:
            port: 6379
            timeout: 20
        db:
          image: postgres:9.4
          environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=travis_ci_test
          port_check:
            port: 5432
            timeout: 45
ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - ruby:2.6.0
  - node:9.0.0
  - yarn:1.17.3
